import { PromptI } from './models/interfaces';

export const prompts: PromptI[] = [
  {
    id: 'prompt_1',
    author: 'John Doe',
    goal: 'Write a blog post',
    prompt: 'What are the benefits of exercise?',
    tags: ['fitness', 'health'],
  },
  {
    id: 'prompt_2',
    author: 'Jane Smith',
    goal: 'Create a presentation',
    prompt: 'Explain the principles of quantum mechanics',
    note: 'Use visual aids',
    tags: ['physics', 'science'],
  },
  {
    id: 'prompt_3',
    author: 'Mark Johnson',
    goal: 'Write a short story',
    prompt: 'Write about a detective solving a mysterious case',
    tags: ['mystery', 'fiction'],
  },
  {
    id: 'prompt_4',
    author: 'Sarah Williams',
    goal: 'Compose a song',
    prompt: 'Write lyrics for a love song',
    note: 'Make it upbeat',
    tags: ['music', 'love'],
  },
  {
    id: 'prompt_5',
    author: 'David Brown',
    goal: 'Design a logo',
    prompt: 'Create a logo for a new tech startup',
    note: 'Incorporate elements of artificial intelligence',
    tags: ['design', 'technology'],
  },
  {
    id: 'prompt_6',
    author: 'Emily Taylor',
    goal: 'Prepare a speech',
    prompt: 'Discuss the importance of education in society',
    tags: ['education', 'society'],
  },
  {
    id: 'prompt_7',
    author: 'Michael Anderson',
    goal: 'Write a poem',
    prompt: 'Compose a haiku about nature',
    tags: ['poetry', 'nature'],
  },
  {
    id: 'prompt_8',
    author: 'Amy Wilson',
    goal: 'Create a recipe',
    prompt: 'Develop a recipe for a healthy breakfast smoothie',
    note: 'Include a variety of fruits and vegetables',
    tags: ['food', 'recipe'],
  },
  {
    id: 'prompt_9',
    author: 'Alex Thompson',
    goal: 'Write a research paper',
    prompt: 'Explore the effects of climate change on marine life',
    tags: ['environment', 'research'],
  },
  {
    id: 'prompt_10',
    author: 'Sam Robinson',
    goal: 'Design a website',
    prompt: 'Create a website for an online clothing store',
    note: 'Make it user-friendly and visually appealing',
    tags: ['web design', 'fashion'],
  },
];
